In [8]:
import torch

# Creating the graph
x = torch.tensor(1.0, requires_grad = True)
y = torch.tensor(2.0)
z = x * y


In [23]:

# Displaying
def displaying(tensors,names):
    for i, name in zip(tensors, names):
        print(f"{name}\ndata: {i.data}\nrequires_grad: {i.requires_grad}\n\
    grad: {i.grad}\ngrad_fn: {i.grad_fn}\nis_leaf: {i.is_leaf}\n")

In [10]:
print(z.backward())

None


In [11]:
# Creating the graph
x = torch.tensor(1.0, requires_grad = True)
z = x ** 3
z.backward() #Computes the gradient 
print(x.grad.data) #Prints '3' which is dz/dx 

tensor(3.)


In [17]:
z.grad_fn

In [24]:
displaying([x,z],"xz")

x
data: 1.0
requires_grad: True
    grad: 3.0
grad_fn: None
is_leaf: True

z
data: 1.0
requires_grad: True
    grad: None
grad_fn: <PowBackward0 object at 0x7f27ccbc1430>
is_leaf: False



<ipython-input-23-582d1f383b2c>:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  grad: {i.grad}\ngrad_fn: {i.grad_fn}\nis_leaf: {i.is_leaf}\n")


{}

In [35]:
import autograd.numpy as np
from autograd import grad

def fun(x, y):
    z = x**2+3*x*y+y**2
    return z
fun_grad = grad(fun)
fun_grad(2.,1.)

IndexError: tuple index out of range

In [33]:
fun_grad


<function autograd.wrap_util.unary_to_nary.<locals>.nary_operator.<locals>.nary_f(*args, **kwargs)>

In [36]:
import autograd.numpy as np   # Thinly-wrapped version of Numpy
from autograd import grad

def taylor_sine(x):  # Taylor approximation to sine function
    ans = currterm = x
    i = 0
    while np.abs(currterm) > 0.001:
        currterm = -currterm * x**2 / ((2 * i + 3) * (2 * i + 2))
        ans = ans + currterm
        i += 1
    return ans

grad_sine = grad(taylor_sine)

In [37]:
grad_sine

<function autograd.wrap_util.unary_to_nary.<locals>.nary_operator.<locals>.nary_f(*args, **kwargs)>

In [38]:
grad_sine(np.pi)


-0.9998995297042174

In [44]:
import autograd.numpy as np
from autograd import grad

def sigmoid(x):
    return 0.5 * (np.tanh(x / 2.) + 1)

def logistic_predictions(weights, inputs):
    # Outputs probability of a label being true according to logistic model.
    return sigmoid(np.dot(inputs, weights))

def training_loss(weights):
    # Training loss is the negative log-likelihood of the training labels.
    preds = logistic_predictions(weights, inputs)
    label_probabilities = preds * targets + (1 - preds) * (1 - targets)
    return -np.sum(np.log(label_probabilities))

# Build a toy dataset.
inputs = np.array([[0.52, 1.12,  0.77],
                   [0.88, -1.08, 0.15],
                   [0.52, 0.06, -1.30],
                   [0.74, -2.49, 1.39]])
targets = np.array([True, True, False, True])

# Define a function that returns gradients of training loss using Autograd.
training_gradient_fun = grad(training_loss)

# Optimize weights using gradient descent.
weights = np.array([0.0, 0.0, 0.0])
print("Initial loss:", training_loss(weights))
for i in range(100):
    weights -= training_gradient_fun(weights) * 0.01

print("Trained loss:", training_loss(weights))

Initial loss: 2.772588722239781
Trained loss: 1.067270675787016


In [42]:
training_gradient_fun

<function autograd.wrap_util.unary_to_nary.<locals>.nary_operator.<locals>.nary_f(*args, **kwargs)>

In [50]:
a = torch.tensor([1,2,3],dtype=torch.float64,requires_grad=True)

In [51]:
a

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)

In [52]:
b = a.exp()

In [53]:
b


tensor([ 2.7183,  7.3891, 20.0855], dtype=torch.float64, grad_fn=<ExpBackward>)

In [54]:
c = b.exp()

In [55]:
c

tensor([1.5154e+01, 1.6182e+03, 5.2849e+08], dtype=torch.float64,
       grad_fn=<ExpBackward>)

In [56]:
input = torch.ones([2, 2], requires_grad=False)
w1 = torch.tensor(2.0, requires_grad=True)
w2 = torch.tensor(3.0, requires_grad=True)
w3 = torch.tensor(4.0, requires_grad=True)

l1 = input * w1
l2 = l1 + w2
l3 = l1 * w3
l4 = l2 * l3
loss = l4.mean()


print(w1.data, w1.grad, w1.grad_fn)
# tensor(2.) None None

print(l1.data, l1.grad, l1.grad_fn)
# tensor([[2., 2.],
#         [2., 2.]]) None <MulBackward0 object at 0x000001EBE79E6AC8>

print(loss.data, loss.grad, loss.grad_fn)

tensor(2.) None None
tensor([[2., 2.],
        [2., 2.]]) None <MulBackward0 object at 0x7f27c78b3be0>
tensor(40.) None <MeanBackward0 object at 0x7f27c78b32b0>


<ipython-input-56-635a6dee7c7c>:16: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(l1.data, l1.grad, l1.grad_fn)
<ipython-input-56-635a6dee7c7c>:20: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(loss.data, loss.grad, loss.grad_fn)


In [57]:
loss.backward()

print(w1.grad, w2.grad, w3.grad)
# tensor(28.) tensor(8.) tensor(10.)
print(l1.grad, l2.grad, l3.grad, l4.grad, loss.grad)

tensor(28.) tensor(8.) tensor(10.)
None None None None None


<ipython-input-57-3e32cbe2b5f1>:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(l1.grad, l2.grad, l3.grad, l4.grad, loss.grad)


In [59]:
z= torch.ones([2, 2], requires_grad=False)

In [62]:
z.size()

torch.Size([2, 2])

In [94]:
a = torch.tensor(3.0,dtype=torch.float64,requires_grad=True)

In [95]:
c = a**2

In [96]:
c

tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>)

In [97]:
a.grad

In [98]:
c

tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>)

In [99]:
f1 = c.grad_fn

In [100]:
f1

In [101]:
a.is_leaf

True

In [102]:
c.is_leaf

False

In [103]:
c.retain_grad()

In [104]:
c

tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>)

In [105]:
c.is_leaf


False

In [106]:
d = c.exp()

In [107]:
d.backward()

In [110]:
c.grad

tensor(8103.0839, dtype=torch.float64)

In [112]:
a = torch.tensor([1.0, 3.0], requires_grad=True)
b = a + 2
print(b._version) # 0

loss = (b * b).mean()
# b[0] = 1000.0
print(b._version) # 1

loss.backward()

0
0


In [113]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf)
# tensor([10.,  5.,  2.,  3.], requires_grad=True) True

a[:] = 0
print(a, a.is_leaf)
# tensor([0., 0., 0., 0.], grad_fn=<CopySlices>) False

loss = (a*a).mean()
loss.backward()

tensor([10.,  5.,  2.,  3.], requires_grad=True) True
tensor([0., 0., 0., 0.], grad_fn=<CopySlices>) False


RuntimeError: leaf variable has been moved into the graph interior

In [114]:
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
a.add_(10.) # 或者 a += 10.

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [119]:
# 方法一
a = torch.tensor([10., 5., 2., 3.], requires_grad=True)
print(a, a.is_leaf, id(a))
# tensor([10.,  5.,  2.,  3.], requires_grad=True) True 2501274822696

a.data.fill_(45)
# 或者 a.detach().fill_(10.)
print(a, a.is_leaf, id(a))
# tensor([10., 10., 10., 10.], requires_grad=True) True 2501274822696

loss = (a*a).mean()
loss.backward()
print(a.grad)
# tensor([5., 5., 5., 5.])

tensor([10.,  5.,  2.,  3.], requires_grad=True) True 139808828904768
tensor([45., 45., 45., 45.], requires_grad=True) True 139808828904768
tensor([22.5000, 22.5000, 22.5000, 22.5000])
